name: Gerar PDFs UFMT

on:
  workflow_dispatch:

jobs:
  gerar-pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install -y wget unzip xvfb

      - name: Instalar bibliotecas Python
        run: |
          pip install playwright PyPDF2
          playwright install chromium

      - name: Executar script para gerar PDFs
        run: xvfb-run --auto-servernum python3 scripts/gerar_pdfs.py

      - name: Upload PDFs Individuais
        uses: actions/upload-artifact@main
        with:
          name: planos-individuais
          path: pdfs_planos/**/*.pdf
          if-no-files-found: warn

      - name: Upload PDFs Agrupados
        uses: actions/upload-artifact@main
        with:
          name: planos-agrupados
          path: pdfs_planos/agrupados/**/*.pdf
          if-no-files-found: warn
