name: Gerar PDFs com Playwright

on:
  workflow_dispatch:

jobs:
  gerar-pdfs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar dependências do sistema e Python
      run: |
        sudo apt update
        sudo apt install -y wget unzip xvfb
        pip install playwright
        playwright install chromium

    - name: Rodar script Python
      run: |
        xvfb-run --auto-servernum python3 scripts/gerar_pdfs.py

    - name: Upload dos PDFs por semestre
      uses: actions/upload-artifact@main
      with:
        name: planos-por-semestre
        path: pdfs_planos/**/*.pdf
